
import { Geist, Geist_Mono } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css"
import "bootstrap/dist/css/bootstrap.min.css"
import Navbar from "./(Components)/navbar/navbar.jsx";
import Providers from "./providers.js";
import "./styles/global.css" ;
import AuthContextProvider from "./context/AuthProvider.jsx";





const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};



export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<AuthContextProvider>
					<Providers>
						<Navbar/>
							{children}
						<h1>Footer</h1>
					</Providers>
				</AuthContextProvider>

			</body>
		</html>
	);
}
