
// import { Geist, Geist_Mono } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css" ;
import "bootstrap/dist/css/bootstrap.min.css" ;




import Providers from "./providers.js";
import AuthContextProvider from "./context/AuthProvider.jsx";
import Navbar from "./components/navbar/Navbar.jsx";
import Footer from "./components/footer/Footer.jsx";
import "./styles/global.css" ;





// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });
// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });
export const metadata = {
	title: "E-Commerce-App",
	description: "Generated by create next app",
};




export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<AuthContextProvider>
					<Providers>
						<Navbar/>
							<main style={{ paddingTop: "60px" }}>
								{children}
							</main>
						<Footer/>
					</Providers>
				</AuthContextProvider>
			</body>
		</html>
	);
}
